---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: defectdojo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: defectdojo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: defectdojo
  interval: 1m0s
  values:
    createPostgresqlSecret: true
    createRabbitMqSecret: true
    createSecret: true
    django:
      ingress:
        activateTLS: false
        enabled: true
      mediaPersistentVolume:
        persistentVolumeClaim:
          create: true
        type: pvc
