---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: defectdojo
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://raw.githubusercontent.com/DefectDojo/django-DefectDojo/helm-charts
